### ISSUE TITLE
problem about opencv version

### ISSUE THREAD

**Issue by JINXvvv** [congchao120/video_synopsis#1]
This code can be run successfully on opencv3.1.
But I want to use opencv3.4 and it failed.
Could you tell me why?

**Comment by congchao120** [comment]
Could you post the error message?

**Comment by JINXvvv** [comment]
[ WARN:0] cvCreateFileCaptureWithPreference: backend FFMPEG doesn't support legacy API anymore.
[ WARN:0] cvCreateFileCaptureWithPreference: backend MSMF doesn't support legacy API anymore.

I have tested each version of opencv and all the environmental configuration are right.

**Comment by congchao120** [comment]
I used some FFMPEG decoding modules for my video dataset. 
It looks like some functions in openCV are out of date and FFMPEG cannot support them anymore. I suggest you to use other functions to read videos, such as VideoCapture, if you are not handling videos with special format.
