### ISSUE TITLE
M_i.at出错

### ISSUE THREAD

**Issue by JINXvvv** [congchao120/video_synopsis#2]
重新判断RT时，貌似在这一句出错int val3 = M_i.at<unsigned short int>(pt3.y, pt3.x);
错误信息为
OpenCV(3.4.3) Error: Assertion failed ((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels())) in cv::Mat::at, file E:\opencv343\rebuild\install\include\opencv2/core/mat.inl.hpp, line 1101

但是重新判断RT之前的判断RT部分，代码并没有出错，请问您知道是为什么吗？

或者您方便的时候可以在微信上交流一下吗，我的微信号是JINXvvv

十分感谢！！！

**Comment by congchao120** [comment]
看起来像是图像通道的问题，例如彩色图像和灰度图像不匹配这样的问题。从语句上看，pt3显然应当是灰度图像

**Comment by JINXvvv** [comment]
> 看起来像是图像通道的问题，例如彩色图像和灰度图像不匹配这样的问题。从语句上看，pt3显然应当是灰度图像

您的源代码里声明了M_i的确是灰度图像，pt3是取自灰度图像M_i的点
Mat M_i = Mat::zeros(s_database.i_height, s_database.i_width, CV_16UC1);

此代码用opencv3.1的时候成功运行，换成opencv3.4时就会出现
OpenCV(3.4.3) Error: Assertion failed ((unsigned)i0 < (unsigned)size.p[0]) in cv::Mat::at, file E:\opencv343\rebuild\install\include\opencv2/core/mat.inl.hpp, line 1100
这样形式的错误。
有没有可能是CV_16UC1和opencv版本的关系，但我换成CV_32SC1 也会报错，不知道是为什么

**Comment by congchao120** [comment]
可以试一下 8UC1，但我认为最好是debug进到程序内部看一下这个assertion语句到底需要什么值才能彻底解决这个问题  。
