### ISSUE TITLE
what is "tube_database.csv"

### ISSUE THREAD

**Issue by smartcai** [congchao120/video_synopsis#3]
Hi, what is the file "D:\\tube_database.csv"?
could u help me share this file?

**Comment by congchao120** [comment]
It's like an intermediate file that exporting/importing information from
video pre-processing to save processing time. Not important for the final
result.

**Comment by smartcai** [comment]
非常感谢！我直接建立一个空的文件也行？

**Comment by smartcai** [comment]
It often crashes here, could u give some suggestion?

Expression: is_block_type_valid(header->block_use)

/**!!!Be careful with the param below!!!**/
			if (find_num > (m_Thres_ObjNum * 3) || frame == NULL || m_iFrame_ind <= skip_begin_frame) {
				m_iFrame_ind += 1;
				continue;
			}
